# Generated by Codex on 2026-04-22

from django.db import migrations, models
import django.db.models.deletion


def assign_company_from_vehicle(apps, schema_editor):
    Company = apps.get_model('accounts', 'Company')
    FuelRecord = apps.get_model('fuel', 'FuelRecord')
    company, _ = Company.objects.get_or_create(
        slug='empresa-principal',
        defaults={'name': 'Empresa Principal'},
    )
    for record in FuelRecord.objects.select_related('vehicle').all():
        record.company_id = record.vehicle.company_id or company.id
        record.save(update_fields=['company'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_company_userprofile_company'),
        ('vehicles', '0002_vehicle_company'),
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelrecord',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuel_records', to='accounts.company', verbose_name='Empresa'),
        ),
        migrations.RunPython(assign_company_from_vehicle, migrations.RunPython.noop),
    ]
