# Generated by Django 4.2.30 on 2026-04-24 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_alter_vehicle_options_alter_vehicle_current_odometer_and_more'),
        ('fuel', '0004_fuelrecord_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrecord',
            name='price_per_liter',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preco por Litro'),
        ),
        migrations.AlterField(
            model_name='fuelrecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_records', to='vehicles.vehicle', verbose_name='Veiculo'),
        ),
    ]
