# Generated by Codex on 2026-04-22

from django.db import migrations, models
import django.db.models.deletion


def assign_company_from_vehicle(apps, schema_editor):
    Company = apps.get_model('accounts', 'Company')
    Trip = apps.get_model('trips', 'Trip')
    company, _ = Company.objects.get_or_create(
        slug='empresa-principal',
        defaults={'name': 'Empresa Principal'},
    )
    for trip in Trip.objects.select_related('vehicle').all():
        trip.company_id = trip.vehicle.company_id or company.id
        trip.save(update_fields=['company'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_company_userprofile_company'),
        ('drivers', '0002_driver_company'),
        ('vehicles', '0002_vehicle_company'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='accounts.company', verbose_name='Empresa'),
        ),
        migrations.RunPython(assign_company_from_vehicle, migrations.RunPython.noop),
    ]
