# Generated by Django 4.2.30 on 2026-04-24 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_alter_vehicle_options_alter_vehicle_current_odometer_and_more'),
        ('trips', '0002_trip_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='purpose',
            field=models.TextField(verbose_name='Proposito'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='service_order',
            field=models.CharField(blank=True, max_length=50, verbose_name='No OS'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.DateTimeField(verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicles.vehicle', verbose_name='Veiculo'),
        ),
    ]
