# Generated by Codex on 2026-04-22

from django.db import migrations, models
import django.db.models.deletion


def assign_default_company(apps, schema_editor):
    Company = apps.get_model('accounts', 'Company')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    company, _ = Company.objects.get_or_create(
        slug='empresa-principal',
        defaults={'name': 'Empresa Principal'},
    )
    UserProfile.objects.filter(company__isnull=True).update(company=company)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nome da empresa')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Identificador')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.company', verbose_name='Empresa'),
        ),
        migrations.RunPython(assign_default_company, migrations.RunPython.noop),
    ]
