# Generated by Codex on 2026-04-22

from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone


def seed_subscription_fields(apps, schema_editor):
    Company = apps.get_model('accounts', 'Company')
    today = timezone.localdate()
    for company in Company.objects.all():
        if company.slug == 'empresa-principal':
            company.plan = 'enterprise'
            company.subscription_status = 'active'
            company.max_users = 0
            company.max_vehicles = 0
            company.subscription_started_at = today
        else:
            company.plan = company.plan or 'starter'
            company.subscription_status = company.subscription_status or 'trial'
            company.max_users = company.max_users or 3
            company.max_vehicles = company.max_vehicles or 10
            company.trial_ends_at = company.trial_ends_at or today + timedelta(days=14)
        company.save(update_fields=[
            'plan', 'subscription_status', 'max_users', 'max_vehicles',
            'trial_ends_at', 'subscription_started_at', 'updated_at',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_company_userprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='billing_document',
            field=models.CharField(blank=True, max_length=30, verbose_name='CPF/CNPJ'),
        ),
        migrations.AddField(
            model_name='company',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail financeiro'),
        ),
        migrations.AddField(
            model_name='company',
            name='max_users',
            field=models.PositiveIntegerField(default=3, help_text='Use 0 para ilimitado.', verbose_name='Limite de usuarios'),
        ),
        migrations.AddField(
            model_name='company',
            name='max_vehicles',
            field=models.PositiveIntegerField(default=10, help_text='Use 0 para ilimitado.', verbose_name='Limite de veiculos'),
        ),
        migrations.AddField(
            model_name='company',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='starter', max_length=30, verbose_name='Plano'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_ends_at',
            field=models.DateField(blank=True, null=True, verbose_name='Fim da assinatura'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_started_at',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio da assinatura'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Periodo de teste'), ('active', 'Ativa'), ('past_due', 'Pagamento pendente'), ('suspended', 'Suspensa'), ('cancelled', 'Cancelada')], default='trial', max_length=30, verbose_name='Status da assinatura'),
        ),
        migrations.AddField(
            model_name='company',
            name='trial_ends_at',
            field=models.DateField(blank=True, null=True, verbose_name='Fim do teste'),
        ),
        migrations.RunPython(seed_subscription_fields, migrations.RunPython.noop),
    ]
