# Generated by Codex on 2026-04-22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_company_userprofile_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Criacao'), ('update', 'Atualizacao'), ('delete', 'Exclusao'), ('login', 'Login'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Acao')),
                ('path', models.CharField(max_length=255, verbose_name='Caminho')),
                ('method', models.CharField(max_length=10, verbose_name='Metodo')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Status HTTP')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Objeto')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={'verbose_name': 'Registro de Auditoria', 'verbose_name_plural': 'Registros de Auditoria', 'ordering': ['-created_at']},
        ),
    ]
