# Generated by Django 4.2.30 on 2026-04-21 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('plate', models.CharField(max_length=8, unique=True, verbose_name='Placa')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('chassis', models.CharField(blank=True, max_length=30, verbose_name='Chassi')),
                ('fuel_type', models.CharField(choices=[('G', 'Gasolina'), ('E', 'Etanol'), ('D', 'Diesel'), ('F', 'Flex'), ('H', 'Híbrido'), ('EL', 'Elétrico')], max_length=2, verbose_name='Combustível')),
                ('capacity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Capacidade (kg)')),
                ('current_odometer', models.IntegerField(default=0, verbose_name='Hodômetro Atual (km)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Foto')),
                ('current_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to='drivers.driver', verbose_name='Motorista Atual')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['plate'],
            },
        ),
    ]
