# Generated by Codex on 2026-04-22

from django.db import migrations, models
import django.db.models.deletion


def assign_default_company(apps, schema_editor):
    Company = apps.get_model('accounts', 'Company')
    Vehicle = apps.get_model('vehicles', 'Vehicle')
    company, _ = Company.objects.get_or_create(
        slug='empresa-principal',
        defaults={'name': 'Empresa Principal'},
    )
    Vehicle.objects.filter(company__isnull=True).update(company=company)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('drivers', '0002_driver_company'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='accounts.company', verbose_name='Empresa'),
        ),
        migrations.RunPython(assign_default_company, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(max_length=8, verbose_name='Placa'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('company', 'plate'), name='unique_vehicle_plate_per_company'),
        ),
    ]
