# Generated by Codex on 2026-04-22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_company_userprofile_company'),
        ('drivers', '0002_driver_company'),
        ('vehicles', '0002_vehicle_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('document_type', models.CharField(choices=[('crlv', 'CRLV'), ('licensing', 'Licenciamento'), ('insurance', 'Seguro'), ('antt', 'ANTT'), ('contract', 'Contrato'), ('inspection', 'Vistoria'), ('driver_license', 'CNH'), ('other', 'Outro')], max_length=30, verbose_name='Tipo')),
                ('title', models.CharField(max_length=120, verbose_name='Titulo')),
                ('number', models.CharField(blank=True, max_length=80, verbose_name='Numero')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Emissao')),
                ('expiration_date', models.DateField(verbose_name='Vencimento')),
                ('file', models.FileField(blank=True, upload_to='documents/', verbose_name='Arquivo')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_documents', to='accounts.company', verbose_name='Empresa')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='drivers.driver', verbose_name='Motorista')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle', verbose_name='Veiculo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['expiration_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='VehicleChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('inspected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da inspecao')),
                ('odometer', models.IntegerField(blank=True, null=True, verbose_name='Hodometro')),
                ('tires_ok', models.BooleanField(default=True, verbose_name='Pneus em bom estado')),
                ('oil_ok', models.BooleanField(default=True, verbose_name='Oleo/fluido ok')),
                ('brakes_ok', models.BooleanField(default=True, verbose_name='Freios ok')),
                ('lights_ok', models.BooleanField(default=True, verbose_name='Luzes e sinalizacao ok')),
                ('safety_items_ok', models.BooleanField(default=True, verbose_name='Itens de seguranca ok')),
                ('cleanliness_ok', models.BooleanField(default=True, verbose_name='Limpeza/conservacao ok')),
                ('status', models.CharField(choices=[('approved', 'Aprovado'), ('attention', 'Requer atencao'), ('blocked', 'Bloqueado')], default='approved', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='checklists/', verbose_name='Foto')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_checklists', to='accounts.company', verbose_name='Empresa')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='drivers.driver', verbose_name='Motorista')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists', to='vehicles.vehicle', verbose_name='Veiculo')),
            ],
            options={
                'verbose_name': 'Checklist de Veiculo',
                'verbose_name_plural': 'Checklists de Veiculos',
                'ordering': ['-inspected_at'],
            },
        ),
    ]
