# Generated by Codex on 2026-04-22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_company_userprofile_company'),
        ('vehicles', '0003_vehicle_documents_checklists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('code', models.CharField(max_length=60, verbose_name='Codigo')),
                ('brand', models.CharField(max_length=80, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=80, verbose_name='Modelo')),
                ('size', models.CharField(blank=True, max_length=40, verbose_name='Medida')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Data de compra')),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo de compra')),
                ('initial_tread_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sulco inicial (mm)')),
                ('current_tread_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sulco atual (mm)')),
                ('position', models.CharField(blank=True, max_length=40, verbose_name='Posicao')),
                ('installed_odometer', models.IntegerField(blank=True, null=True, verbose_name='Km de instalacao')),
                ('status', models.CharField(choices=[('stock', 'Em estoque'), ('installed', 'Instalado'), ('repair', 'Em reparo'), ('retread', 'Recapagem'), ('retired', 'Descartado')], default='stock', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tires', to='accounts.company', verbose_name='Empresa')),
                ('current_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tires', to='vehicles.vehicle', verbose_name='Veiculo atual')),
            ],
            options={'verbose_name': 'Pneu', 'verbose_name_plural': 'Pneus', 'ordering': ['code']},
        ),
        migrations.CreateModel(
            name='TireEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('event_type', models.CharField(choices=[('install', 'Instalacao'), ('rotation', 'Rodizio'), ('removal', 'Remocao'), ('repair', 'Reparo'), ('retread', 'Recapagem'), ('retire', 'Descarte')], max_length=20, verbose_name='Tipo')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data')),
                ('odometer', models.IntegerField(blank=True, null=True, verbose_name='Hodometro')),
                ('position', models.CharField(blank=True, max_length=40, verbose_name='Posicao')),
                ('tread_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sulco medido (mm)')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tire_events', to='accounts.company', verbose_name='Empresa')),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vehicles.tire', verbose_name='Pneu')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tire_events', to='vehicles.vehicle', verbose_name='Veiculo')),
            ],
            options={'verbose_name': 'Evento de Pneu', 'verbose_name_plural': 'Eventos de Pneus', 'ordering': ['-date', '-created_at']},
        ),
        migrations.AddConstraint(
            model_name='tire',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_tire_code_per_company'),
        ),
    ]
