# Generated by Codex on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_tires'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='heading_degrees',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Direcao (graus)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_location_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultima posicao'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_speed_kmh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Velocidade atual (km/h)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='location_source',
            field=models.CharField(blank=True, max_length=80, verbose_name='Origem do rastreamento'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
