# Generated by Django 4.2.30 on 2026-04-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehicle_tracking_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['plate'], 'verbose_name': 'Veiculo', 'verbose_name_plural': 'Veiculos'},
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='current_odometer',
            field=models.IntegerField(default=0, verbose_name='Hodometro Atual (km)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('G', 'Gasolina'), ('E', 'Etanol'), ('D', 'Diesel'), ('F', 'Flex'), ('H', 'Hibrido'), ('EL', 'Eletrico')], max_length=2, verbose_name='Combustivel'),
        ),
    ]
