# Generated by Codex on 2026-04-22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_company_userprofile_company'),
        ('vehicles', '0002_vehicle_company'),
        ('maintenance', '0002_maintenance_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreventiveMaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('service_name', models.CharField(max_length=120, verbose_name='Servico preventivo')),
                ('description', models.TextField(blank=True, verbose_name='Descricao')),
                ('frequency_km', models.IntegerField(blank=True, null=True, verbose_name='Recorrencia por km')),
                ('frequency_days', models.IntegerField(blank=True, null=True, verbose_name='Recorrencia por dias')),
                ('last_service_date', models.DateField(blank=True, null=True, verbose_name='Ultima execucao')),
                ('last_service_km', models.IntegerField(blank=True, null=True, verbose_name='Km da ultima execucao')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Proxima data')),
                ('next_due_km', models.IntegerField(blank=True, null=True, verbose_name='Proximo km')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Critica')], default='medium', max_length=20, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('paused', 'Pausado'), ('completed', 'Concluido')], default='active', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='accounts.company', verbose_name='Empresa')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='vehicles.vehicle', verbose_name='Veiculo')),
            ],
            options={
                'verbose_name': 'Plano de Manutencao Preventiva',
                'verbose_name_plural': 'Planos de Manutencao Preventiva',
                'ordering': ['status', 'next_due_date', 'next_due_km'],
            },
        ),
    ]
