# Generated by Codex on 2026-04-22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_company_userprofile_company'),
        ('drivers', '0002_driver_company'),
        ('vehicles', '0002_vehicle_company'),
        ('maintenance', '0003_preventive_maintenance_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=140, verbose_name='Titulo')),
                ('category', models.CharField(choices=[('maintenance', 'Manutencao'), ('fuel', 'Abastecimento'), ('tires', 'Pneus'), ('damage', 'Avaria'), ('document', 'Documento'), ('other', 'Outro')], default='maintenance', max_length=30, verbose_name='Categoria')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Critica')], default='medium', max_length=20, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('scheduled', 'Agendada'), ('in_progress', 'Em andamento'), ('waiting_parts', 'Aguardando pecas'), ('completed', 'Concluida'), ('cancelled', 'Cancelada')], default='open', max_length=20, verbose_name='Status')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Aberta em')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Data agendada')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluida em')),
                ('odometer', models.IntegerField(blank=True, null=True, verbose_name='Hodometro')),
                ('description', models.TextField(verbose_name='Descricao')),
                ('resolution', models.TextField(blank=True, verbose_name='Resolucao')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo estimado')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo realizado')),
                ('attachment', models.FileField(blank=True, upload_to='work_orders/', verbose_name='Anexo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='accounts.company', verbose_name='Empresa')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='drivers.driver', verbose_name='Motorista')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='vehicles.vehicle', verbose_name='Veiculo')),
            ],
            options={'verbose_name': 'Ordem de Servico', 'verbose_name_plural': 'Ordens de Servico', 'ordering': ['status', '-opened_at']},
        ),
        migrations.CreateModel(
            name='VehicleExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data')),
                ('category', models.CharField(choices=[('fuel', 'Combustivel'), ('maintenance', 'Manutencao'), ('tires', 'Pneus'), ('documents', 'Documentos'), ('insurance', 'Seguro'), ('taxes', 'Taxas e impostos'), ('other', 'Outros')], max_length=30, verbose_name='Categoria')),
                ('cost_center', models.CharField(blank=True, max_length=100, verbose_name='Centro de custo')),
                ('supplier', models.CharField(blank=True, max_length=120, verbose_name='Fornecedor')),
                ('description', models.CharField(max_length=180, verbose_name='Descricao')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('receipt', models.FileField(blank=True, upload_to='expenses/', verbose_name='Comprovante')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_expenses', to='accounts.company', verbose_name='Empresa')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='vehicles.vehicle', verbose_name='Veiculo')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='maintenance.workorder', verbose_name='Ordem de servico')),
            ],
            options={'verbose_name': 'Despesa de Frota', 'verbose_name_plural': 'Despesas de Frota', 'ordering': ['-date', '-created_at']},
        ),
    ]
