# Generated by Django 4.2.30 on 2026-04-24 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_alter_vehicle_options_alter_vehicle_current_odometer_and_more'),
        ('maintenance', '0004_work_orders_expenses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-date'], 'verbose_name': 'Manutencao', 'verbose_name_plural': 'Manutencoes'},
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='description',
            field=models.TextField(verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='next_alert_date',
            field=models.DateField(blank=True, null=True, verbose_name='Alerta prox. manutencao (data)'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='next_alert_km',
            field=models.IntegerField(blank=True, null=True, verbose_name='Alerta prox. manutencao (km)'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenances', to='vehicles.vehicle', verbose_name='Veiculo'),
        ),
    ]
