# Generated by Codex on 2026-04-22

from django.db import migrations, models
import django.db.models.deletion


def assign_default_company(apps, schema_editor):
    Company = apps.get_model('accounts', 'Company')
    Driver = apps.get_model('drivers', 'Driver')
    company, _ = Company.objects.get_or_create(
        slug='empresa-principal',
        defaults={'name': 'Empresa Principal'},
    )
    for driver in Driver.objects.select_related('user').all():
        driver.company_id = company.id
        driver.save(update_fields=['company'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='accounts.company', verbose_name='Empresa'),
        ),
        migrations.RunPython(assign_default_company, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='driver',
            name='cnh',
            field=models.CharField(max_length=20, verbose_name='CNH'),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(fields=('company', 'cnh'), name='unique_driver_cnh_per_company'),
        ),
    ]
