# Generated by Django 4.2.30 on 2026-04-24 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers', '0002_driver_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='address',
            field=models.TextField(blank=True, verbose_name='Endereco'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Disponivel'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
