# Generated by Django 4.2.30 on 2026-04-21 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('type', models.CharField(choices=[('P', 'Preventiva'), ('C', 'Corretiva'), ('E', 'Emergencial')], max_length=1, verbose_name='Tipo')),
                ('date', models.DateField(verbose_name='Data')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Custo')),
                ('odometer', models.IntegerField(verbose_name='Km no Momento')),
                ('workshop', models.CharField(max_length=100, verbose_name='Oficina')),
                ('next_alert_km', models.IntegerField(blank=True, null=True, verbose_name='Alerta próx. manutenção (km)')),
                ('next_alert_date', models.DateField(blank=True, null=True, verbose_name='Alerta próx. manutenção (data)')),
                ('invoice', models.FileField(blank=True, upload_to='maintenance_invoices/', verbose_name='Nota Fiscal')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenances', to='vehicles.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
                'ordering': ['-date'],
            },
        ),
    ]
