# Generated by Django 4.2.30 on 2026-04-21 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('date', models.DateField(verbose_name='Data')),
                ('liters', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Litros')),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço por Litro')),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=8, verbose_name='Custo Total')),
                ('odometer', models.IntegerField(verbose_name='Km no Abastecimento')),
                ('gas_station', models.CharField(max_length=100, verbose_name='Posto')),
                ('receipt', models.FileField(blank=True, upload_to='fuel_receipts/', verbose_name='Nota Fiscal')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_records', to='vehicles.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Abastecimento',
                'verbose_name_plural': 'Abastecimentos',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
