# Generated by Django 4.2.30 on 2026-04-21 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('start_time', models.DateTimeField(verbose_name='Início')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('start_odometer', models.IntegerField(verbose_name='Km Inicial')),
                ('end_odometer', models.IntegerField(blank=True, null=True, verbose_name='Km Final')),
                ('destination', models.CharField(max_length=255, verbose_name='Destino')),
                ('purpose', models.TextField(verbose_name='Propósito')),
                ('service_order', models.CharField(blank=True, max_length=50, verbose_name='Nº OS')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='drivers.driver', verbose_name='Motorista')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicles.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
                'ordering': ['-start_time'],
            },
        ),
    ]
